### ISSUE TITLE
Please release the latest version of the package of npm. Current one is out of date!

### ISSUE THREAD

**Issue by fmlharrison** [react-native-linear-gradient/react-native-linear-gradient#519] opened 2021-02-22 10:32 UTC
Hey! 
Please can you release the latest version of the code for this package on npm so we can get the update you have done since September last year. I am currently having to manually change the dependancy in the podspec file from `React` to `React-Core` to get my project to build. 

From looking at the latest code on GitHub it looks like you have made the above change but haven't released it. Please could you do that.

Thanks for this great package btw

**Comment by fmlharrison** [comment] 2021-02-22 10:39
Please see https://github.com/facebook/react-native/issues/29633#issuecomment-694187116 for and explanation on why this is important.

**Comment by tuddman** [comment] 2021-02-23 15:46
duplicate of https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/505

**Comment by aminmahrami** [comment] 2022-06-27 14:53
@GantMan @dgladkov @nickhudkins any chance we can get a new release please?

**Comment by GantMan** [comment] 2022-06-30 20:19
I keep not doing this.  Would one of you be interested in being added as a maintainer so I don't keep forgetting?  Please provide your NPM username.

**Comment by aminmahrami** [comment] 2022-06-30 20:22
Sure, my username is `aminmahrami` @GantMan

**Comment by GantMan** [comment] 2022-06-30 21:24
@aminmahrami - you are now a maintainer on the repo and NPMjs

**Comment by friederbluemle** [comment] 2022-07-01 08:45
2.6.0 is now available which contains the podspec fix (#500) 🎉

**Closed by friederbluemle** 2022-07-01 08:45 UTC
